title: Annika's Portfolio
theme: jekyll-theme-minimal
description: This is Annika's github portfolio - work in progress.
logo: "/assets/bike-krupunder.jpg" # path of site logo, e.g. "/assets/images/logo.png"
